---
- name: Set environment variable for deployment config
  hosts: localhost
  tasks:
  - name: Set environment variable
    command: oc set env dc/easytravel-loadgen ET_PROBLEMS=LoginProblems -n travel-apps
