---
- name: Login to OpenShift cluster
  hosts: all
  connection: ssh
  tasks:
    - name: Login to OpenShift cluster
      command: oc login -u opentlc-mgr -p SlWBsd1OpQbvSJzS --insecure-skip-tls-verify https://api.cluster-f4zmk.f4zmk.sandbox2653.opentlc.com:6443
    - name: Set environment variable for deployment config
      command: oc set env dc/easytravel-loadgen ET_BACKEND_URL=http://easytravel-www:8080 ET_PROBLEMS=LoginProblems -n travel-apps
